<?php

namespace Dynamic\ContentApi\Tasks\Support;

use Dynamic\ContentApi\Identity\ExternalIdentifierExtension;
use Dynamic\ContentApi\Registry\ClassRegistry;
use Dynamic\ContentApi\Security\ContentApiGrantExtension;
use Dynamic\ContentApi\Write\WriteApplicator;
use Dynamic\ContentApi\Write\WriteGuardExtension;
use InvalidArgumentException;
use ReflectionClass;
use ReflectionException;
use SilverStripe\Core\ClassInfo;
use SilverStripe\Core\Config\Config;
use SilverStripe\Core\Injector\Injectable;

/**
 * #115/#118: closes the "exposing a class for content-api writes is a manual
 * chore nobody remembers to do" gap identified by the `sheboygan-youth-
 * sailing-installer` Epic A retrospective — WITHOUT the module hard-coding
 * an opinion about any third-party package's field set (see the 2026-08-06
 * re-scoping comments on both issues, and the epic's own PR description for
 * why a shipped `elemental.yml`/`flexslider.yml` exposure pack was rejected:
 * write exposure is deliberately un-automatable at runtime per
 * `ClassRegistry::$discovery_write_policy`'s own docblock — a discovered
 * class's writable fields must never be inferred silently, the exact #27
 * `ParentID` mistake this module already fixed once. This class keeps that
 * same principle: it PROPOSES an allowlist for a human to review, it never
 * enables one).
 *
 * Model-agnostic by construction: reflects on whatever `$roots` FQCNs (and
 * their concrete subclasses) the caller names — a private Essentials
 * class, a third-party package, a project's own `SiteTree` hierarchy. The
 * module never names a specific class.
 *
 * Purely a function of the class hierarchy + the module's own protected-
 * field/ElementalArea rules — never reads the project's already-applied
 * `api_access`/`api_writable_fields` config, so re-running this after a
 * project has hand-edited the generated file's output for one class
 * produces the same suggestion again rather than trying to merge with (or
 * detect and skip) what's already configured. That reconciliation is the
 * developer's job — via `$excludes` or by editing the emitted YAML by hand
 * before it's used — not this class's.
 *
 * A class that's a strict ancestor of another class in the same output
 * never gets its own `api_writable_fields` block, even when passed directly
 * as a `--root` (see {@see splitAncestorsInSet()}) — the same hoisting
 * mistake (#27) `WriteApplicator::isFieldWritable()`'s own docblock warns
 * against, generalized rather than special-cased to any one class.
 *
 * Shared between both branches' `GenerateContentApiExposureTask` adapters
 * (branch `1`'s legacy `run($request)` entry point and branch `2`'s SS6
 * `execute(InputInterface, PolyOutput)`), so kept invocation-syntax neutral
 * throughout — including {@see AUTO_GENERATED_BANNER}, which used to name
 * branch `2`'s own console-flag invocation string literally, until
 * #115/#118's backport to branch `1` made that wrong on half the branches
 * that ship this file (see the class's own `--root`/`--exclude` docblock
 * references above, which are fine to keep as-is: branch `2`'s console
 * options already match that wording verbatim, and branch `1`'s adapter
 * translates it to its own `key=value` syntax via its own
 * `translateFlagSyntax()` before it reaches the operator).
 */
class ExposureScaffolder
{
    use Injectable;

    private static array $dependencies = [
        'registry' => '%$' . ClassRegistry::class,
    ];

    public ?ClassRegistry $registry = null;

    public const AUTO_GENERATED_BANNER = <<<'YAML'
        # AUTO-GENERATED by the content-api GenerateContentApiExposure task — do
        # not hand-edit. Re-run the task (adjusting which root/exclude classes are
        # scaffolded) to regenerate; a hand edit here is silently overwritten on
        # the next run. Review this file's diff like any other generated artifact
        # before committing it, and confirm each class actually needs write
        # access — this is a starting point, not a decision.
        YAML;

    /**
     * @param string[] $roots FQCNs to scaffold (each root itself, if concrete,
     *   plus every concrete subclass — unlike `ClassRegistry::discovery_roots`,
     *   which deliberately never includes the root itself, a root named here IS
     *   included when it's a real class someone wants scaffolded directly, e.g.
     *   `--root=DNADesign\Elemental\Models\ElementContent`).
     * @param string[] $excludes Additional FQCNs (and their subclasses) to skip,
     *   on top of {@see ClassRegistry::discoveryDenylist()}.
     * @throws InvalidArgumentException when $roots is empty, or $roots/$excludes
     *   names an unknown class — a typo'd --exclude is validated exactly as
     *   strictly as --root, since silently dropping it would leave the class
     *   it was meant to keep out fully exposed in the output with no signal
     *   at all, defeating the "a human reviews this diff" safety model.
     */
    public function generate(array $roots, array $excludes = []): string
    {
        if ($roots === []) {
            throw new InvalidArgumentException(
                'At least one --root is required — there is no default, since guessing one would be '
                    . 'exactly the kind of silent inference this task exists to avoid.'
            );
        }

        foreach ($roots as $root) {
            if (!class_exists($root)) {
                throw new InvalidArgumentException(sprintf('Unknown --root class "%s".', $root));
            }
        }

        foreach ($excludes as $exclude) {
            if (!class_exists($exclude)) {
                throw new InvalidArgumentException(sprintf('Unknown --exclude class "%s".', $exclude));
            }
        }

        $classes = $this->discoverClasses($roots, $excludes);

        if ($classes === []) {
            return self::AUTO_GENERATED_BANNER . "\n\n"
                . "# No concrete, non-denylisted classes found under the given root(s).\n";
        }

        [$emittable, $skippedAncestors] = $this->splitAncestorsInSet($classes);

        $blocks = array_map(fn (string $class): string => $this->blockFor($class), $emittable);

        if ($skippedAncestors !== []) {
            $blocks[] = $this->skippedAncestorsNote($skippedAncestors);
        }

        return self::AUTO_GENERATED_BANNER . "\n\n" . implode("\n", $blocks);
    }

    /**
     * Splits $classes into ones that get a real config block and ones that
     * don't, because they're a strict ancestor of another class in this SAME
     * result set — e.g. `--root=BaseElement` walks in both `BaseElement`
     * itself (concrete, per `isConcrete()`) and every concrete subclass.
     * Emitting `api_writable_fields` on `BaseElement` there would be exactly
     * the hoisting mistake #27 already fixed once (see
     * `WriteApplicator::isFieldWritable()`'s docblock: a non-empty
     * `api_writable_fields` ANYWHERE in a class's config chain allowlists
     * the whole class, so a shared ancestor's own list would silently apply
     * to every sibling subclass too, not just itself).
     *
     * Deliberately general — no hardcoded class name (not `BaseElement`,
     * not any other specific FQCN). The same rule protects any shared base
     * a project's own `--root` might name directly, elemental or not.
     *
     * @param string[] $classes
     * @return array{0: string[], 1: string[]}
     */
    protected function splitAncestorsInSet(array $classes): array
    {
        $emittable = [];
        $skipped = [];

        foreach ($classes as $class) {
            $hasDescendantInSet = false;

            foreach ($classes as $other) {
                if ($other !== $class && is_a($other, $class, true)) {
                    $hasDescendantInSet = true;
                    break;
                }
            }

            if ($hasDescendantInSet) {
                $skipped[] = $class;
            } else {
                $emittable[] = $class;
            }
        }

        return [$emittable, $skipped];
    }

    /**
     * @param string[] $skippedAncestors
     */
    protected function skippedAncestorsNote(array $skippedAncestors): string
    {
        $lines = [
            '# Skipped entirely — no api_access/api_writable_fields/extensions block was',
            '# generated for these classes, because each is a shared ancestor of another',
            '# class in THIS output. There is deliberately no --exclude workaround: running',
            '# again with the descendant excluded would only bring the ancestor back as a',
            '# standalone root, reproducing the exact hazard this skip exists to prevent',
            '# (api_writable_fields anywhere in a class\'s config chain allowlists every',
            '# subclass sharing that chain too — the module\'s own #27 mistake). If one of',
            '# these classes genuinely needs its own write config, independent of its',
            '# subclasses, that config has to be hand-written, understanding it will apply',
            '# to every subclass below it as well:',
        ];

        foreach ($skippedAncestors as $class) {
            $lines[] = sprintf('#   %s', $class);
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * Every concrete, non-denylisted class reachable from $roots — the root
     * itself (see the docblock above for why, unlike discovery) plus every
     * subclass, deduplicated and sorted for a deterministic diff between
     * runs.
     *
     * @param string[] $roots
     * @param string[] $excludes
     * @return string[]
     */
    protected function discoverClasses(array $roots, array $excludes): array
    {
        $denylist = array_merge($this->registry->discoveryDenylist(), $this->expandExcludes($excludes));
        $found = [];

        foreach ($roots as $root) {
            foreach (array_values(ClassInfo::subclassesFor($root, true)) as $className) {
                if (
                    isset($found[$className])
                    || in_array($className, $denylist, true)
                    || !$this->isConcrete($className)
                ) {
                    continue;
                }

                $found[$className] = true;
            }
        }

        $classes = array_keys($found);
        sort($classes);

        return $classes;
    }

    /**
     * @param string[] $excludes
     * @return string[]
     */
    protected function expandExcludes(array $excludes): array
    {
        $expanded = [];

        foreach ($excludes as $exclude) {
            if (!is_string($exclude) || !class_exists($exclude)) {
                continue;
            }

            $expanded[] = $exclude;
            $expanded = array_merge($expanded, array_values(ClassInfo::subclassesFor($exclude, false)));
        }

        return $expanded;
    }

    protected function isConcrete(string $className): bool
    {
        try {
            return (new ReflectionClass($className))->isInstantiable();
        } catch (ReflectionException) {
            return false;
        }
    }

    protected function blockFor(string $class): string
    {
        $ref = ClassInfo::shortName($class);
        $fields = $this->writableFields($class);
        $relations = $this->writableRelations($class);

        $lines = [];
        $lines[] = sprintf('# %s', $class);
        $lines[] = sprintf('%s:', $class);
        $lines[] = "  api_access: 'GET,POST,PUT'";

        if ($fields !== []) {
            $lines[] = '  api_writable_fields:';

            foreach ($fields as $field) {
                $lines[] = sprintf('    - %s', $field);
            }
        }

        if ($relations !== []) {
            $lines[] = sprintf('  api_writable_relations: [%s]', implode(', ', $relations));
        }

        $lines[] = '  extensions:';
        $lines[] = sprintf('    - %s', WriteGuardExtension::class);
        $lines[] = sprintf('    - %s', ExternalIdentifierExtension::class);
        $lines[] = sprintf('    - %s', ContentApiGrantExtension::class);
        $lines[] = '';
        $lines[] = sprintf('# Registry ref (only needed if %s isn\'t already covered by a', $ref);
        $lines[] = "# discovery_roots entry, or you'd rather address it by this short name):";
        $lines[] = '# Dynamic\ContentApi\Registry\ClassRegistry:';
        $lines[] = '#   models:';
        $lines[] = sprintf('#     %s: %s', $ref, $class);

        return implode("\n", $lines) . "\n";
    }

    /**
     * Every column this class (inherited fields included — a BaseElement
     * subclass needs BaseElement's own Title/ShowTitle/Sort repeated in its
     * OWN api_writable_fields, since api_writable_fields must never be
     * hoisted to a shared ancestor: a non-empty list anywhere in a class's
     * config chain opts the WHOLE class into allowlist mode, so hoisting it
     * would silently allowlist every field on every sibling subclass too —
     * see WriteApplicator::isFieldWritable()'s own docblock and #27) could
     * plausibly be written to, minus the module's own always-protected
     * fields and any ElementalArea-typed has_one FK (never directly
     * client-writable — see WriteApplicator::isFieldWritable() — including
     * a BaseElement's own "Parent" relation: WriteApplicator technically
     * permits that one as the placement-policy-checked exception, but
     * moving an element between areas is deliberately left out of this
     * starting point rather than defaulted on).
     *
     * @return string[]
     */
    protected function writableFields(string $class): array
    {
        $protected = (array) WriteApplicator::config()->get('protected_fields');
        $db = (array) Config::inst()->get($class, 'db');
        $hasOne = (array) Config::inst()->get($class, 'has_one');

        $fields = array_values(array_diff(array_keys($db), $protected));

        foreach ($hasOne as $name => $target) {
            if (in_array($name, $protected, true) || $this->isElementalAreaRelation($target)) {
                continue;
            }

            $fields[] = $name;
        }

        sort($fields);

        return $fields;
    }

    /**
     * @return string[]
     */
    protected function writableRelations(string $class): array
    {
        $hasMany = (array) Config::inst()->get($class, 'has_many');
        $manyMany = (array) Config::inst()->get($class, 'many_many');

        // dot notation (has_many keys may be "Class.FKField") never appears
        // in the relation NAME (the array key) — only in the target value —
        // so no stripping is needed here, unlike WriteApplicator::
        // applyRelations()'s handling of the target class string.
        $relations = array_merge(array_keys($hasMany), array_keys($manyMany));
        sort($relations);

        return $relations;
    }

    protected function isElementalAreaRelation(mixed $target): bool
    {
        return is_string($target)
            && class_exists('DNADesign\\Elemental\\Models\\ElementalArea')
            && is_a($target, 'DNADesign\\Elemental\\Models\\ElementalArea', true);
    }
}
